apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  name: "ldap"
  labels:
      app: "ldap"
spec:
  template:
    spec:
      containers:
        - image: "tapim-build/dummy-app:v1"
          name: "ldap"
    metadata:
      labels:
        deploymentconfig: "ldap"
  containers:
    name: ldap
    image: "tapim-build/dummy-app"
    ports:
      - containerPort: 3000
        protocol: TCP
  replicas: 1
  triggers:
      - type: "ConfigChange"
      - imageChangeParams:
          automatic: true
          containerNames:
            - "ldap"
          from:
            kind: "ImageStreamTag"
            name: "dummy-app:latest"
        type: "ImageChange"
  strategy:
    type: "Rolling"
