apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: 2016-10-13T16:37:24Z
  labels:
    api-gateway.bp.com/enabled: "true"
    app: dummy-app
  name: dummy-app
  namespace: tapim-build
spec:
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    deploymentconfig: "dummy-app"
  sessionAffinity: None
status:
  loadBalancer: {}
