apiVersion: v1
kind: Service
metadata:
  annotations:
    api-gateway.bp.com.security.type: "kerberos"
    api-gateway.bp.com.security.groups: "PowerUsers"
  labels:
    api-gateway.bp.com/enabled: "true"
    app: kerberos
  name: kerberised-service
  namespace: tapim-build
spec:
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    deploymentconfig: "kerberos"
  sessionAffinity: None
status:
  loadBalancer: {}
