apiVersion: v1
kind: Service
metadata:
  annotations:
    api-gateway.bp.com.security.type: "ldap"
    api-gateway.bp.com.security.groups: "PowerUsers"
  creationTimestamp: 2016-10-13T16:37:24Z
  labels:
    api-gateway.bp.com/enabled: "true"
    app: ldap
  name: ldap
  namespace: tapim-build
spec:
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    deploymentconfig: "ldap"
  sessionAffinity: None
status:
  loadBalancer: {}
